[package]
name = "riscv-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
riscv = "0.12.1"
riscv-rt = { version = "0.13.0", optional = true }
vcell = "0.1.0"

[features]
rt = ["riscv-rt"]
